### ISSUE TITLE
cookie-factory dependency fails to compile with latest nightly

### ISSUE THREAD

**Issue by rex4539** [str4d/rage#69]
## Environment

* OS: `macOS 10.15.4 (19E224g)`
* rage version: `master`

```
% git clone git@github.com:str4d/rage.git
Cloning into 'rage'...
remote: Enumerating objects: 180, done.
remote: Counting objects: 100% (180/180), done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 2087 (delta 102), reused 142 (delta 80), pack-reused 1907
Receiving objects: 100% (2087/2087), 681.39 KiB | 1.96 MiB/s, done.
Resolving deltas: 100% (1268/1268), done.
% cd rage
% cargo build
   Compiling libc v0.2.66
   Compiling typenum v1.11.2
   Compiling cfg-if v0.1.10
   Compiling proc-macro2 v1.0.8
   Compiling byteorder v1.3.2
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.14
   Compiling memchr v2.3.0
   Compiling getrandom v0.1.14
   Compiling semver-parser v0.7.0
   Compiling lazy_static v1.4.0
   Compiling cc v1.0.50
   Compiling log v0.4.8
   Compiling arrayvec v0.4.12
   Compiling subtle v1.0.0
   Compiling opaque-debug v0.2.3
   Compiling ryu v1.0.2
   Compiling autocfg v1.0.0
   Compiling version_check v0.1.5
   Compiling spin v0.5.2
   Compiling subtle v2.2.2
   Compiling nodrop v0.1.14
   Compiling untrusted v0.7.0
   Compiling byte-tools v0.3.1
   Compiling ppv-lite86 v0.2.6
   Compiling regex-syntax v0.6.14
   Compiling static_assertions v0.3.4
   Compiling fake-simd v0.1.2
   Compiling remove_dir_all v0.5.2
   Compiling unicode-width v0.1.7
   Compiling quick-error v1.2.3
   Compiling base64 v0.11.0
   Compiling cookie-factory v0.3.0
   Compiling arrayref v0.3.6
   Compiling termcolor v1.1.0
   Compiling bech32 v0.7.2
   Compiling thread_local v1.0.1
   Compiling semver v0.9.0
error[E0415]: identifier `s` is bound more than once in this parameter list
   --> /Users/rex/.cargo/registry/src/github.com-1ecc6299db9ec823/cookie-factory-0.3.0/src/internal.rs:144:36
    |
144 |     fn skip(s: WriteContext<Self>, s: usize) -> GenResult<Self>
    |                                    ^ used as parameter more than once

error: aborting due to previous error

For more information about this error, try `rustc --explain E0415`.
error: could not compile `cookie-factory`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by str4d** [comment]
This sounds like a new compiler error. What version of Rust were you compiling with?

**Comment by rex4539** [comment]
Latest nightly.

**Comment by str4d** [comment]
Confirmed that on Ubuntu it builds fine with latest stable (`1.41.0`), and fails with latest nightly (`1.43.0-nightly (07a34df18 2020-02-08)`), so this isn't a macOS-specific problem. I'll open an upstream issue.

**Comment by str4d** [comment]
Opened https://github.com/rust-bakery/cookie-factory/issues/31

**Comment by str4d** [comment]
The issue is fixed upstream, but a new release has not been made yet. I'll leave this open until we can pull in the updated dependency.
